
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QueueTime' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QueueTime
    pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git'
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'SinchRTC'

	pod 'FBSDKCoreKit'
	pod 'FBSDKLoginKit'
	pod 'FacebookCore'
	pod 'FacebookLogin'
	pod 'Firebase/Messaging'


  target 'QueueTimeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QueueTimeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end